#!/usr/bin/env bash
# Installs — and, run again, updates — the Supervisor → Lead → Peer room:
#   1. the /supervisor skill            → ~/.claude/skills/supervisor
#   2. a Claude runtime per Lead/Peer seat (its role as an output style,
#      sharing your settings, skills, and one token) and the Codex launcher
#                                        → ~/.config/slp-room
#   3. the room's profiles and providers → ~/.paseo/config.json (backup kept alongside)
#   4. paseo daemon reload
# From a checkout: ./install.sh   Piped: curl -fsSL <raw>/install.sh | bash
# Options: --skill-only, --paseo-only, --no-reload. SLP_REF picks a branch or tag.
set -euo pipefail

REPO="yanmad27/my-orchestrate-skill"
TARBALL_URL="${SLP_TARBALL_URL:-https://codeload.github.com/$REPO/tar.gz/${SLP_REF:-main}}"
ROOM_HOME="${SLP_ROOM_HOME:-$HOME/.config/slp-room}"

DO_SKILL=1
DO_PASEO=1
RELOAD=1
for arg in "$@"; do
  case "$arg" in
    --skill-only) DO_PASEO=0 ;;
    --paseo-only) DO_SKILL=0 ;;
    --no-reload) RELOAD=0 ;;
    *) echo "Unknown option: $arg" >&2; exit 1 ;;
  esac
done
if [ "$DO_SKILL" = 0 ] && [ "$DO_PASEO" = 0 ]; then
  echo "--skill-only and --paseo-only are mutually exclusive; pass at most one." >&2
  exit 1
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Source: this checkout, or the repository tarball when piped.
if [ -n "${BASH_SOURCE[0]:-}" ] && [ -f "${BASH_SOURCE[0]}" ] \
  && [ -d "$(dirname "${BASH_SOURCE[0]}")/skills/supervisor" ]; then
  SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
  command -v curl >/dev/null 2>&1 || { echo "curl is required to download $REPO." >&2; exit 1; }
  curl -fsSL "$TARBALL_URL" | tar -xz -C "$WORK" || { echo "Failed to download $TARBALL_URL" >&2; exit 1; }
  SRC="$(find "$WORK" -mindepth 1 -maxdepth 1 -type d | head -1)"
fi
VERSION="$(tr -d '[:space:]' < "$SRC/version.txt")"

# --- 1. skill -------------------------------------------------------------------

if [ "$DO_SKILL" = 1 ]; then
  SKILLS="$HOME/.claude/skills"
  mkdir -p "$SKILLS"
  rm -rf "$SKILLS/supervisor"
  cp -R "$SRC/skills/supervisor" "$SKILLS/supervisor"
  echo "Installed skill: $SKILLS/supervisor"
  # v1 installed the same role as "orchestrate"; leaving it would compete with /supervisor.
  if [ -f "$SKILLS/orchestrate/SKILL.md" ] && grep -q '^name: orchestrate$' "$SKILLS/orchestrate/SKILL.md"; then
    rm -rf "$SKILLS/orchestrate"
    echo "Removed legacy skill: $SKILLS/orchestrate"
  fi
fi

if [ "$DO_PASEO" = 1 ]; then
  command -v jq >/dev/null 2>&1 || { echo "jq is required but not installed. Install jq and re-run." >&2; exit 1; }

  # --- 2. role prompts, Claude runtimes, Codex launcher ---------------------------
  # Paseo has no per-agent system prompt. Each Claude seat gets its own Claude Code
  # runtime (CLAUDE_CONFIG_DIR) whose output style carries protocol + role, sharing the
  # user's settings, skills, plugins, and CLAUDE.md, and one auth token. Codex gets the
  # Peer prompt as developer instructions through a launcher.

  CLAUDE_HOME="$HOME/.claude"
  mkdir -p "$ROOM_HOME/bin"
  for role in lead peer; do
    {
      printf '<!-- Generated by install.sh (my-orchestrate-skill %s). Re-run it to update; do not edit. -->\n\n' "$VERSION"
      cat "$SRC/skills/supervisor/PROTOCOL.md"
      printf '\n---\n\n'
      cat "$SRC/skills/supervisor/roles/$role.md"
    } > "$ROOM_HOME/$role.md"

    RUNTIME="$ROOM_HOME/claude-$role"
    mkdir -p "$RUNTIME/output-styles" "$RUNTIME/skills"
    {
      printf -- '---\nname: slp-%s\ndescription: Supervisor → Lead → Peer room, %s seat\nkeep-coding-instructions: true\n---\n\n' "$role" "$role"
      cat "$ROOM_HOME/$role.md"
    } > "$RUNTIME/output-styles/slp-$role.md"

    # The user's settings, with the role's output style, and without this plugin: a Lead
    # or Peer must never load the Supervisor skill.
    USER_SETTINGS='{}'
    if [ -f "$CLAUDE_HOME/settings.json" ]; then
      if jq -e 'type == "object"' "$CLAUDE_HOME/settings.json" >/dev/null 2>&1; then
        USER_SETTINGS="$(cat "$CLAUDE_HOME/settings.json")"
      else
        echo "WARNING: $CLAUDE_HOME/settings.json is not a JSON object; the $role runtime starts from empty settings." >&2
      fi
    fi
    printf '%s' "$USER_SETTINGS" | jq --arg style "slp-$role" '
      .outputStyle = $style
      | .enabledPlugins = ((.enabledPlugins // {})
          | with_entries(if (.key | startswith("orchestrate@")) then .value = false else . end))
    ' > "$RUNTIME/settings.json"

    for shared in plugins agents commands CLAUDE.md; do
      if [ -e "$CLAUDE_HOME/$shared" ] && { [ -L "$RUNTIME/$shared" ] || [ ! -e "$RUNTIME/$shared" ]; }; then
        ln -sfn "$CLAUDE_HOME/$shared" "$RUNTIME/$shared"
      fi
    done
    find "$RUNTIME/skills" -mindepth 1 -maxdepth 1 -type l -exec rm -f {} +
    if [ -d "$CLAUDE_HOME/skills" ]; then
      for skill in "$CLAUDE_HOME/skills"/*; do
        case "$(basename "$skill")" in supervisor|orchestrate) continue ;; esac
        [ -e "$skill" ] && ln -sfn "$skill" "$RUNTIME/skills/$(basename "$skill")"
      done
    fi
  done
  rm -f "$ROOM_HOME/bin/claude-lead" "$ROOM_HOME/bin/claude-peer"  # launchers of an earlier version

  # Shared auth: `claude setup-token` output, saved by the user in $ROOM_HOME/oauth-token.
  OAUTH_TOKEN="${SLP_CLAUDE_OAUTH_TOKEN:-}"
  if [ -z "$OAUTH_TOKEN" ] && [ -f "$ROOM_HOME/oauth-token" ]; then
    OAUTH_TOKEN="$(tr -d '[:space:]' < "$ROOM_HOME/oauth-token")"
  fi
  if [ -z "$OAUTH_TOKEN" ]; then
    echo "WARNING: no Claude token for the Lead/Peer runtimes. Run 'claude setup-token', save the" >&2
    echo "  sk-ant-oat01-… line to $ROOM_HOME/oauth-token (chmod 600), and re-run install.sh —" >&2
    echo "  or log in once per runtime: CLAUDE_CONFIG_DIR=$ROOM_HOME/claude-lead claude (and claude-peer)." >&2
  fi

  CODEX_BIN="$(command -v codex || true)"
  if [ -z "$CODEX_BIN" ]; then
    echo "WARNING: codex is not on PATH; the codex-peer launcher will look it up each time it runs." >&2
    CODEX_BIN=codex
  fi
  # Codex takes the prompt as a TOML literal string, which cannot contain '''.
  if grep -qF "'''" "$ROOM_HOME/peer.md"; then
    echo "roles/peer.md or PROTOCOL.md contains ''' and cannot be passed to Codex; remove it and re-run." >&2
    exit 1
  fi
  cat > "$ROOM_HOME/bin/codex-peer" <<LAUNCHER
#!/bin/sh
# Generated by install.sh: Codex with the room's peer role as developer instructions.
exec "$CODEX_BIN" -c "developer_instructions='''\$(cat "$ROOM_HOME/peer.md")'''" "\$@"
LAUNCHER
  chmod +x "$ROOM_HOME/bin/codex-peer"
  echo "Rendered room runtimes and prompts: $ROOM_HOME"

  # --- 3. Paseo config ------------------------------------------------------------

  # With no token the env key is dropped, so a per-runtime login keeps working.
  jq --arg dir "$ROOM_HOME" --arg token "$OAUTH_TOKEN" '
    walk(if type == "string" then gsub("@@ROOM_HOME@@"; $dir) else . end)
    | .agents.providers |= map_values(
        if .env.CLAUDE_CODE_OAUTH_TOKEN == "@@CLAUDE_OAUTH_TOKEN@@" then
          (if $token == "" then del(.env.CLAUDE_CODE_OAUTH_TOKEN) else .env.CLAUDE_CODE_OAUTH_TOKEN = $token end)
        else . end)
  ' "$SRC/paseo/config.snippet.json" > "$WORK/snippet.json"

  PASEO_DIR="$HOME/.paseo"
  CONFIG="$PASEO_DIR/config.json"
  mkdir -p "$PASEO_DIR"
  # The config and its backups may hold the Claude token: keep them private.
  umask 077
  [ -f "$CONFIG" ] || echo '{"version":1}' > "$CONFIG"
  chmod 600 "$CONFIG"
  cp "$CONFIG" "$CONFIG.bak-$(date +%Y%m%d%H%M%S)"

  # The snippet's profiles (matched by id, or by name when an old install left no id) and
  # providers are owned by this script: each run replaces them with the snippet's version.
  # v1 profiles and the v1 claude-worker provider are removed. Everything else is kept.
  MERGE='
    ($snip[0].daemon.agentProfiles) as $new
    | ["agent_profile_orchestrate_cheap_worker", "agent_profile_orchestrate_worker",
       "agent_profile_orchestrate_expensive_worker", "agent_profile_orchestrate_reviewer",
       "agent_profile_orchestrate_codex_advisor"] as $legacyIds
    | ["Cheap worker", "Worker", "Expensive worker", "Reviewer", "Codex advisor"] as $legacyNames
    | (($new | map(.id)) + $legacyIds) as $ownedIds
    | (($new | map(.name)) + $legacyNames) as $ownedNames
    | def owned: if .id == null then (.name as $n | $ownedNames | index($n)) != null
                 else (.id as $i | $ownedIds | index($i)) != null end;
    .daemon.agentProfiles = (((.daemon.agentProfiles // []) | map(select(owned | not))) + $new)
    | (.daemon.agentProfiles | map(.provider)) as $used
    | .agents.providers = ((.agents.providers // {}) + $snip[0].agents.providers)
    | if (.agents.providers["claude-worker"].description // "") == "Delegated worker — cannot spawn or control other agents"
         and ($used | index("claude-worker")) == null
      then del(.agents.providers["claude-worker"]) else . end
  '
  TMP="$(mktemp "$CONFIG.XXXXXX")"
  jq --slurpfile snip "$WORK/snippet.json" "$MERGE" "$CONFIG" > "$TMP"
  REMOVED="$(jq -r --slurpfile after "$TMP" '
    [.daemon.agentProfiles[]?.name] - [$after[0].daemon.agentProfiles[].name] | join(", ")' "$CONFIG")"
  mv "$TMP" "$CONFIG"
  echo "Updated Paseo config: $CONFIG (backup saved alongside it)"
  echo "  Room profiles: $(jq -r '[.daemon.agentProfiles[].name] | join(", ")' "$WORK/snippet.json")"
  echo "  Room providers: $(jq -r '.agents.providers | keys | join(", ")' "$WORK/snippet.json")"
  [ -z "$OAUTH_TOKEN" ] || echo "  Claude runtimes share the token from $ROOM_HOME/oauth-token"
  [ -z "$REMOVED" ] || echo "  Removed v1 profiles: $REMOVED"
  DUPES="$(jq -r '[.daemon.agentProfiles[].name] | group_by(.) | map(select(length > 1)[0]) | join(", ")' "$CONFIG")"
  [ -z "$DUPES" ] || echo "WARNING: you also have your own profile(s) named $DUPES; rename yours so the room picks the right one." >&2

  if [ "$(jq -r '.daemon.mcp.injectIntoAgents // false' "$CONFIG")" != "true" ]; then
    echo "WARNING: daemon.mcp.injectIntoAgents is not enabled in $CONFIG" >&2
    echo "The Supervisor and Lead agents will not have the create_agent tool without it." >&2
    echo "Enable it by setting daemon.mcp.enabled: true and daemon.mcp.injectIntoAgents: true" >&2
  fi

  # --- 4. reload --------------------------------------------------------------------

  if [ "$RELOAD" = 0 ]; then
    echo "Run 'paseo daemon reload' to load the updated profiles and providers."
  elif command -v paseo >/dev/null 2>&1 && paseo daemon reload; then
    :
  else
    echo "WARNING: could not run 'paseo daemon reload'; run it (or restart Paseo) yourself." >&2
  fi
fi

echo "my-orchestrate-skill $VERSION installed."
